### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ThierryThevenet** [Bdaya-Dev/jose#5]
Hello, we may use your lib for our data wallet https;//talao.io but what is not clear to us is what we have to do on top of  publishing the license in our list of licenses.

Could you elaborate precisely what you expect us to do or even choose a MIT license or Apache 2.0 license ?
Thank you

**Comment by ahmednfwela** [comment]
this is a fork of https://github.com/appsup-dart/jose , so you may consult them on the license
